### ISSUE TITLE
Imagens

### ISSUE THREAD

**Issue by gustavulima** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e1-proj-web-t14-pmv-ads-2023-1-e1-proj-web-t14-g3-mmiau#2]
![kanban_trello](https://user-images.githubusercontent.com/44280078/233848258-f87db172-cac7-4679-a21a-2db8bad9c570.png)

**Comment by marciufilho94** [comment]
![Projeto (3)](https://user-images.githubusercontent.com/131212345/236110657-cb6b60a8-7613-4379-a678-b9c54aa43343.jpg)

**Comment by marciufilho94** [comment]
![Diagrama de classes](https://user-images.githubusercontent.com/131212345/236987970-d373b4e3-652e-4180-a2c5-463b06a7f9b5.jpg)

**Comment by marciufilho94** [comment]
![Diagrama de componentes](https://user-images.githubusercontent.com/131212345/236988241-46534002-8945-4873-b833-1e4fcd5c4fb0.PNG)
